apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex
  labels:
    app: cortex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      containers:
        - name: cortex
          image: ghcr.io/nesohq/bgce-archive/cortex:6cf91b4031cb96fe136116e9cc496a70e375cf52
          ports:
            - containerPort: 3345
          env:
            - name: VERSION
              value: "1.0.0"
            - name: MODE
              value: "debug"
            - name: SERVICE_NAME
              value: "cortex"
            - name: HTTP_PORT
              value: "3345"
            - name: MIGRATION_SOURCE
              value: "migrations"
            - name: JWT_SECRET
              value: "asdf-secret"
            - name: RABBITMQ_URL
              value: "amqp://admin:admin@rabbitmq:5672"
            - name: RMQ_RECONNECT_DELAY
              value: "5"
            - name: RMQ_RETRY_INTERVAL
              value: "600"
            - name: RMQ_QUEUE_PREFIX
              value: "cortex-dev"
            - name: READ_REDIS_URL
              value: "redis://redis:6379"
            - name: WRITE_REDIS_URL
              value: "redis://redis:6379"
            - name: BGCE_DB_DSN
              value: "postgres://postgres:postgres@postgres:5432/bgce?sslmode=disable"
            - name: BGCE_DB_DRIVER
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: cortex-service
  labels:
    app: cortex
spec:
  selector:
    app: cortex
  type: NodePort
  ports:
    - protocol: TCP
      port: 3345
      targetPort: 3345
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: bgce
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
